Add kron
FlagOpen/FlagGems pull request #383
Opened 2024-12-31 02:13 UTC by AdvancedCompiler

### PR Category
 Operator 
### Type of Change
New Feature

### Description

Implement kron operator
### Issue

#259 

### Progress

- [ ] Change is properly reviewed (1 reviewer required, 2 recommended).
- [ ] Change is responded to an issue.
- [ ] Change is fully covered by a UT.

### Performance
![微信图片_20241231101248](https://github.com/user-attachments/assets/4748cb62-3f7f-4d0d-a072-aa5ff986c044)

2025-01-10 02:10 UTC, iclementine commented on benchmark/core_shapes.yaml
> +  shapes:
shapes for benchmarking is too small to saturate gpu.

2025-01-10 02:59 UTC, iclementine requested changes

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +    pid = tle.program_id(0).to(tl.int64)
It is not need to explicitly cast every integer to int64. Operations would promote types as needed.

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +        return torch.empty(out_shape, device=A.device, dtype=A.dtype)
Type promotion need to be taken into consideration.

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +    if not out_shape:
In what cases would `out_shape` evaluate to `False`? I think it would always be a tuple of integers, with at least 2 elements.

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +        kron_kernel[grid](
You need to specify onto which device the kernel is going to be launched, or else it always launched onto device 0.

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +    batch_size = int(torch.prod(torch.tensor(out_shape[:-2]))) if out_shape[:-2] else 1
calculating shapes with torch APIs is somehow overkill and make a data denpendent control flow. I advise just using builtin tuples and lists.

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +    C = torch.empty(out_shape, device=A.device, dtype=A.dtype)
type promotion need to be considered

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +    for i in range(batch_size):
Launching multiple kernels in a loop would serialize them and may lead to low gpu utilization if `M, N` is small. I advise trying to launch just 1 kernel with more CTAs to do this.

2025-01-10 02:59 UTC, iclementine commented on src/flag_gems/ops/kron.py
> +    if A.dim() <= 1 and B.dim() <= 1 and A.numel() > 0 and B.numel() > 0:
`A.numel() == 0 or B.numel() == 0` is already handled at the begining.

2025-01-10 02:59 UTC, iclementine commented on tests/test_special_ops.py
> +@pytest.mark.parametrize("dtype", FLOAT_DTYPES)
Add test for integer dtypes and boolean dtypes?

2025-01-10 02:59 UTC, iclementine commented on tests/accuracy_utils.py
> +    [(1, 1, 1), (2, 2, 2)],
Add some test cases with zeor-dimensional tensor and zero-sized tensors.

2025-01-10 07:53 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +    pid = tle.program_id(0).to(tl.int64)
During calculations with tensors of size (256, 256) and (256, 256), the indices exceed the valid range of int32 but are not automatically converted to int64.

2025-01-10 08:17 UTC, tongxin reviewed
The current implementation can only deal with 2d matrices. Can we extend it to nd matrices?

2025-01-10 08:17 UTC, tongxin commented on src/flag_gems/ops/kron.py
> +        return torch.empty(out_shape, device=A.device, dtype=A.dtype)
I think it's OK to ignore this degenerate case for sake of lower overhead.

2025-01-10 08:17 UTC, tongxin commented on src/flag_gems/ops/kron.py
> +        else [1] * (2 - len(tensor_a.shape)) + list(tensor_a.shape)
Please avoid the syntax as confusing as this.

2025-01-13 12:08 UTC, AdvancedCompiler commented on benchmark/core_shapes.yaml
> +  shapes:
ok, i will change it

2025-01-14 08:36 UTC, ph0375 commented on benchmark/core_shapes.yaml
> +  shapes:
If the tensor shape is too large, there may not be enough GPU memory available.

2025-01-14 08:37 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +        return torch.empty(out_shape, device=A.device, dtype=A.dtype)
fixed.

2025-01-14 08:37 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +    if not out_shape:
fixed.

2025-01-14 08:37 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +    batch_size = int(torch.prod(torch.tensor(out_shape[:-2]))) if out_shape[:-2] else 1
fixed.

2025-01-14 08:37 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +    C = torch.empty(out_shape, device=A.device, dtype=A.dtype)
fixed.

2025-01-14 08:37 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +    for i in range(batch_size):
fixed.

2025-01-14 08:38 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +    if A.dim() <= 1 and B.dim() <= 1 and A.numel() > 0 and B.numel() > 0:
fixed.

2025-01-14 08:38 UTC, ph0375 commented on tests/test_special_ops.py
> +@pytest.mark.parametrize("dtype", FLOAT_DTYPES)
added.

2025-01-14 08:38 UTC, ph0375 commented on tests/accuracy_utils.py
> +    [(1, 1, 1), (2, 2, 2)],
added.

2025-01-14 08:39 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +        else [1] * (2 - len(tensor_a.shape)) + list(tensor_a.shape)
fixed

2025-01-14 08:39 UTC, ph0375 commented on src/flag_gems/ops/kron.py
> +        return torch.empty(out_shape, device=A.device, dtype=A.dtype)
fixed

2025-03-06 06:11 UTC, iclementine approved these changes

2025-03-06 07:51 UTC, merged